name: TravelPact
options:
  bundleIdPrefix: com.travelpact
  deploymentTarget:
    iOS: 17.0
  createIntermediateGroups: true
  groupSortPosition: top
  generateEmptyDirectories: true
  
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.travelpact.app
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: 5.9
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
    ENABLE_PREVIEWS: YES
    SWIFT_EMIT_LOC_STRINGS: YES
    INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
    INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
    INFOPLIST_KEY_UILaunchScreen_Generation: YES
    INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
    INFOPLIST_KEY_NSCameraUsageDescription: "TravelPact needs access to your camera to take profile photos"
    INFOPLIST_KEY_NSPhotoLibraryUsageDescription: "TravelPact needs access to your photo library to select profile photos"
    INFOPLIST_KEY_NSLocationWhenInUseUsageDescription: "TravelPact needs your location to connect you with nearby travelers"

packages:
  Supabase:
    url: https://github.com/supabase-community/supabase-swift
    from: 2.0.0

targets:
  TravelPact:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: TravelPact
        excludes:
          - "**/.DS_Store"
          - "Info.plist"
    dependencies:
      - package: Supabase
        product: Supabase
    settings:
      base:
        INFOPLIST_FILE: TravelPact/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.travelpact.app
        TARGETED_DEVICE_FAMILY: 1
        SUPPORTS_MACCATALYST: NO
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: YES
    info:
      path: TravelPact/Info.plist
      properties:
        CFBundleDisplayName: TravelPact
        CFBundleName: TravelPact
        CFBundleShortVersionString: 1.0.0
        CFBundleVersion: "1"
        LSRequiresIPhoneOS: true
        UIRequiredDeviceCapabilities: [armv7]
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        NSCameraUsageDescription: TravelPact needs access to your camera to take profile photos
        NSPhotoLibraryUsageDescription: TravelPact needs access to your photo library to select profile photos  
        NSLocationWhenInUseUsageDescription: TravelPact needs your location to connect you with nearby travelers
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSupportsIndirectInputEvents: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
    preBuildScripts:
      - script: |
          # Copy environment variables to Info.plist
          if [ -f "${PROJECT_DIR}/.env.local" ]; then
            while IFS='=' read -r key value; do
              /usr/libexec/PlistBuddy -c "Set :$key $value" "${TARGET_BUILD_DIR}/${INFOPLIST_PATH}" 2>/dev/null || \
              /usr/libexec/PlistBuddy -c "Add :$key string $value" "${TARGET_BUILD_DIR}/${INFOPLIST_PATH}"
            done < "${PROJECT_DIR}/.env.local"
          fi
        name: Load Environment Variables
        inputFiles:
          - ${PROJECT_DIR}/.env.local
        outputFiles: []

schemes:
  TravelPact:
    build:
      targets:
        TravelPact: all
    run:
      config: Debug
      environmentVariables:
        SUPABASE_URL: $(SUPABASE_URL)
        SUPABASE_ANON_PUBLIC: $(SUPABASE_ANON_PUBLIC)
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release